config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get "up" => "rails/health#show", as: :rails_health_check

  root "welcome#index"
  
  get ":nick_name", to: "users#show"
  post '/lanugage/change', to: 'language#change'
  
  resources :welcome
  
  resources :tags do
    member do
      get "articles"
    end
  end
    
  resources :profile, only: [] do
    collection do
      get "my_published_articles"
      get "my_draft_articles"

      get "my_comments"
      get "my_rejected_comments"
      get "my_pending_comments"
      get "my_approved_comments"
      
      get "my_received_comments"
      get "my_received_rejected_comments"
      get "my_received_approved_comments"
      get "my_received_pending_comments"
    end
  end

  resources :articles, except: %i[index] do
    member do
      post "publish"
      post "unpublish"
      post "like"
      post "dislike"
      get "likes"
    end

    collection do
      get "search"
    end

    resources :comments do
      member do
        post "mark_as_approved"
        post "mark_as_rejected"
        post "mark_as_pending"
      end
    end
  end

  namespace "api" do
    resources :articles, only: %i[show index]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
    enum :status, [ :pending, :approved, :rejected ]
    belongs_to :article
    belongs_to :user
    validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_article, only: %i[create update destroy edit mark_as_approved mark_as_rejected]
    before_action :find_comment, only: %i[update destroy edit mark_as_approved mark_as_rejected]
    before_action :reject_request_if_user_of_comment_is_not_current_user, only: %i[update destroy edit]
    before_action :reject_request_if_status_of_comment_is_not_pending, only: %i[edit update destroy]
    before_action :reject_request_if_current_user_is_not_owner_of_comments_article, only: %i[mark_as_approved mark_as_rejected]
    before_action :reject_request_if_comment_status_is_not_pending, only: %i[mark_as_approved mark_as_rejected]
    after_action :set_status, only: %i[create]
    
    def create
        @comment = current_user.comments.build(comment_params)
        if @article.comments << @comment
            redirect_to @article, notice: t("comment_notifications.create")
        else
            redirect_to @article, alert: t("comment_notifications.create_failed")
        end
    end

    def update
        if @comment.update(comment_params)
            redirect_to request.referer, notice: t("comment_notifications.update")
        else
            redirect_to request.referer, alert: t("comment_notifications.update_failed")
        end
    end

    def destroy
        if @comment.destroy
            redirect_to request.referer, notice: t("comment_notifications.destroy")
        else
            redirect_to request.referer, alert: t("comment_notifications.destroy_failed")
        end
    end
    
    def edit; end

    def mark_as_approved
        if @comment.approved!
            redirect_to request.referer, notice: t("comment_notifications.mark_as_approved")
        else
            redirect_to request.referer, alert: t("comment_notifications.mark_as_approved_failed")
        end
    end

    def mark_as_rejected
        if @comment.rejected!
            redirect_to request.referer, notice: t("comment_notifications.mark_as_rejected")
        else
            redirect_to request.referer, alert: t("comment_notifications.mark_as_rejected_failed")
        end
    end
    
    private
        def comment_params
            params.require(:comment).permit(:body)
        end

        def find_article
            @article = Article.find(params[:article_id])
        end
 
        def find_comment
            @comment = @article.comments.find(params[:id])
        end

        def reject_request_if_user_of_comment_is_not_current_user
            if @comment.user != current_user
                redirect_to my_pending_comments_profile_index_path, alert: t("comment_notifications.owner")
            end
        end

        def reject_request_if_status_of_comment_is_not_pending
            unless @comment.pending?
                redirect_to my_pending_comments_profile_index_path, alert: t("comment_notifications.not_pending_comment_manipulate")
            end
        end

        def reject_request_if_current_user_is_not_owner_of_comments_article
            unless current_user.articles.include?(@comment.article)
                redirect_to my_received_pending_comments_profile_index_path, alert: t("comment_notifications.belong_article")
            end
        end

        def reject_request_if_comment_status_is_not_pending
            unless @comment.pending?
                redirect_to my_received_pending_comments_profile_index_path, alert: t("comment_notifications.not_pending_status_manipulate")
            end
        end

        def set_status
            if @article.user == @comment.user
                @comment.approved!
            else
                @comment.pending!
            end
        end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def get_comment_header_color(comment)
        if comment.article.user == current_user
            comment.approved? ? "bg-success" : comment.pending? ? "bg-warning" : "bg-danger"
        else
            return "" if comment.user != current_user
            comment.approved? ? "bg-success" : comment.pending? ? "bg-warning" : "bg-danger"
        end
    end

    def is_approvable?(comment)
        comment.article.user == current_user && comment.pending?
    end

    def is_manipulated?(comment)
        comment.user == current_user && comment.pending?
    end
end

app/views/comments/_article_comments_list.html.erb
<div class="container">
    <div class="d-flex justify-content-center mb-2">
        <h1><%= t("article_comments_list.title") %></h1>
    </div>

    <% if comments.any? %>
        <% comments.each do |comment| %>
            <% if current_user == comment.user%>
                <div class="d-flex flex-row-reverse mb-2">
                    <div style="width:75%">
                        <%= render partial: "comments/comment", locals: { comment: comment } %>
                    </div>
                </div>
            <% else %>
                <div class="d-flex mb-2">
                    <div style="width:75%">
                        <%= render partial: "comments/comment", locals: { comment: comment } %>
                    </div>
                </div>
            <% end %>
        <% end %>
    <% else %>
        <h3><%= t("article_comments_list.no_comments") %></h3>
    <% end %>
</div>

app/views/comments/_comment.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-between align-items-center <%= get_comment_header_color(comment)%>">
    <%= link_to "/#{comment.user.nick_name}" do %>
      <div class="d-flex align-items-center">
        <%= render partial:"shared/profile_circle", locals: { user: comment.user, circle: "circle2" }%>
        <span class="nickname2"><%= format_nick_name(comment.user)%></span>
      </div>
    <% end %>
    <div style="font-weight:w100;font-size:0.9rem;">
      <%= render partial: "comments/comment_datetime", locals:{ comment: comment } %>
    </div>
  </div>

  <div class="card-body">
    <p class="card-text">
      <%= comment.body %>
    </p>

    <% if comment.user == current_user && !comment.approved? %>
      <div class="mb-2">
        <span class="<%= comment.rejected? ? "text-danger" : "text-warning" %>">
          <% if comment.pending? %>
            <%= t("comment.pending_comment_message") %>
          <% else %>
            <%= t("comment.rejected_comment_message") %>
          <% end %>
        <span>
      </div>
    <% end %>
    
    <div class="d-flex">
      <% if is_approvable?(comment) %>
        <div class="d-flex me-1">
          <%= render partial: "comments/comment_approve_button", locals: { comment: comment } %>
        </div>
      <% end %>

      <% if is_manipulated?(comment)%>
        <div class="me-1">
          <%= link_to edit_article_comment_path(comment.article, comment), class: "btn btn-warning me-1" do %>
            <i class="bi bi-pencil-square"></i>
          <% end %>
        </div>

        <div class="me-1">
          <%= button_to article_comment_path(comment.article, comment), method: :delete, class: "btn btn-danger" do %>
            <i class="bi bi-trash3-fill"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_comment_approve_button.html.erb
<div class="d-flex">
    <%= button_to mark_as_approved_article_comment_path(comment.article,comment), :class => "btn btn-success me-1" do %>
        <i class="bi bi-check-lg"></i>
    <% end %>
    <%= button_to mark_as_rejected_article_comment_path(comment.article, comment), :class => "btn btn-danger" do %>
        <i class="bi bi-x-lg"></i>
    <% end %>
</div>

app/views/comments/_comment_datetime.html.erb
<span>
    <i class="bi bi-clock"></i>
    <%= time_tag comment.created_at, format: :short %>
</span>

app/views/comments/_comment_list.html.erb
<% comments.each do |comment| %>
   <div class="mb-3">
      <%= render partial: "comments/comment", locals: { comment: comment } %>
   </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ article, comment ] do |form| %>
    <div class="d-flex">
        <%= form.text_area :body, class: "form-control comment-textarea", rows: 1, placeholder: t("comment_form.type_comment") %>
        <%= button_tag(type: 'submit', class: 'btn btn-primary comment-send-button') do %>
            <i class="bi bi-send-fill"></i>
        <% end %>
    </div>
<% end %>

app/views/comments/edit.html.erb
<div class="row">
    <div class="offset-3 col-6">
        <h3 class="mb-3"><%= t("comment_edit.title")%></h3>
        <%= render partial: "comments/form", locals: { article: @article, comment: @comment } %>
    </div>
</div>