config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get "up" => "rails/health#show", as: :rails_health_check

  root "welcome#index"
  
  get ":nick_name", to: "users#show"
  post '/lanugage/change', to: 'language#change'
  
  resources :welcome
  
  resources :tags do
    member do
      get "articles"
    end
  end
    
  resources :profile, only: [] do
    collection do
      get "my_published_articles"
      get "my_draft_articles"

      get "my_comments"
      get "my_rejected_comments"
      get "my_pending_comments"
      get "my_approved_comments"
      
      get "my_received_comments"
      get "my_received_rejected_comments"
      get "my_received_approved_comments"
      get "my_received_pending_comments"
    end
  end

  resources :articles, except: %i[index] do
    member do
      post "publish"
      post "unpublish"
      post "like"
      post "dislike"
      get "likes"
    end

    collection do
      get "search"
    end

    resources :comments do
      member do
        post "mark_as_approved"
        post "mark_as_rejected"
        post "mark_as_pending"
      end
    end
  end

  namespace "api" do
    resources :articles, only: %i[show index]
  end
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { maximum: 140 }
    has_rich_text :content
    scope :published_articles, -> { where(published: true).order(created_at: :desc) }
    belongs_to :user
    has_many :article_likes, dependent: :destroy
    has_many :users, through: :article_likes
    has_many :comments, dependent: :destroy
    has_many :article_tags, dependent: :destroy
    has_many :tags, through: :article_tags
    
    def publish
        self.published = true
        save
    end

    def unpublish
        self.published = false
        save
    end
end

app/controllers/api/articles_controller.rb
module Api
    class ArticlesController < ApplicationController
        def show
            render json: Article.find_by(id: params[:id], published: true)
        end

        def index
            render json: Article.published_articles
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, except: %i[show likes search]
    before_action :find_article, only: %i[show like dislike likes publish unpublish update destroy edit]
    before_action :reject_request_if_current_user_is_not_owner_of_article, only: %i[publish unpublish update destroy edit]
    before_action :reject_request_if_article_is_published, only: %i[update destroy edit]

    def update
       if @article.update(articles_params)
            redirect_to @article, notice: t("article_notifications.update")
       else
            render :edit, status: :unprocessable_entity
        end
    end

    def create
        @article = Article.create(articles_params)
        if current_user.articles << @article
            redirect_to @article, notice: t("article_notifications.create")
        else
            render :new, status: :unprocessable_entity
        end
    end

    def new
        @article = Article.new
    end

    def edit; end

    def show
        raise ActiveRecord::RecordNotFound if !@article.published && @article.user != current_user
    end

    def destroy
        if @article.destroy
            redirect_to"/#{current_user.nick_name}", notice: t("article_notifications.destroy")
        else
            redirect_to @article, alert: t("article_notifications.destroy_failed")
        end
    end

    def publish
        if @article.publish
            redirect_to @article, notice: t("article_notifications.publish")
        else
            redirect_to @article, alert: t("article_notifications.publish_failed")
        end
    end

    def unpublish
        if @article.unpublish
            redirect_to @article, notice: t("article_notifications.unpublish")
        else
            redirect_to @article, notice:  t("article_notifications.unpublish_failed")
        end
    end

    def like
        @article.article_likes << ArticleLike.new(user_id: current_user.id)

        redirect_to @article
    end

    def dislike
        like = @article.article_likes.where(user_id: current_user.id).first
        @article.article_likes.destroy(like)
        
        redirect_to @article 
    end

    def likes; end

    def search
        key = "%#{params[:keyword]}%"

        if params[:just_tags] == "1"
            @articles = Article
                .joins(:tags)
                .where("tags.name LIKE ?", key)
                .where(published: true)
                .order(created_at: :desc)
                .distinct
        else
            @articles = Article
                .left_outer_joins(:rich_text_content, :tags)
                .where("title LIKE ? OR action_text_rich_texts.body LIKE ? OR tags.name LIKE ?", key, key, key)
                .where(published: true)
                .order(created_at: :desc)
                .distinct
        end
    end

    private
        def articles_params
            params.require(:article).permit(:title, :content, :published, tag_ids: [])
        end

        def find_article
            @article = Article.find(params[:id])
        end

        def reject_request_if_current_user_is_not_owner_of_article
            if @article.user != current_user
                redirect_to @article, 
                alert: t("article_notifications.owner")
            end
        end

        def reject_request_if_article_is_published
            if @article.published
                redirect_to @article, alert: t("article_notifications.state")
            end
        end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def format_article_content(article)
        return t("article.empty_content") if article.content.empty?
        return article.content.to_plain_text if article.content.to_plain_text.length <= 20
        "#{article.content.to_plain_text[0..19]}..."
    end

    def article_content(article)
        return t("article.empty_content") if article.content.empty?
        article.content
    end

    def format_article_title(article)
        return article.title if article.title.length <= 20
        "#{article.title[0..19]}..."
    end

    def get_article_header_background_color(article)
        return "" if current_user != article.user
        article.published ? "bg-success" : "bg-secondary"
    end

    def get_approved_comments_or_current_users_pending_comments(article)
        article.comments
            .where(status: :approved)
            .or(article.comments.where(user: current_user, status: :pending))
            .order(created_at: :desc)
    end

    def get_number_of_approved_comments_or_current_users_pending_comments(article)
        article.comments
            .where(status: :approved)
            .or(article.comments.where(user: current_user, status: :pending))
            .count
    end

    def is_liked?(article,user)
        ArticleLike.where(article_id: article.id, user_id: user.id).any?
    end
end

app/views/articles/_article.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-between align-items-center <%= get_article_header_background_color(article) %>">
    <%= link_to "/#{article.user.nick_name}" do %>
      <div class="d-flex align-items-center">
        <%= render partial:"shared/profile_circle", locals: { user: article.user, circle: "circle2" }%>
        <span class="nickname2"><%= format_nick_name(article.user) %></span>
      </div>
    <% end %>
    
    <small class="text-muted">
      <%= render partial: "articles/article_datetime", locals: { article: article } %>
    </small>
  </div>

  <div class="card-body">
    <div class="d-flex">
      <h5 class="card-title">
        <%= format_article_title(article) %>
      </h5>
    </div>

    <p class="card-text">
      <%= format_article_content(article) %>
    </p>

    <div class="d-flex justify-content-between align-items-center">
      <div class="card-text">
        <small class="text-muted">
          <%= render partial: "articles/number_of_likes", locals: { article: article } %>
        </small>
        <small class="text-muted">
          <%= render partial: "articles/number_of_comments", locals: { article: article } %>
        </small>
      </div>

      <%= link_to article, class: "btn btn-outline-primary" do %>
        <i class="bi bi-arrow-right-circle"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_article_datetime.html.erb
<span>
    <i class="bi bi-clock"></i>
    <%= time_tag article.created_at, format: :short%>
</span>

app/views/articles/_article_form.html.erb
<%= form_with(model: article) do |form| %>
    
    <% if article&.errors&.any? %>
        <ul class="list-group mb-3">
            <% article.errors.each do |error| %>
                <li class="list-group-item list-group-item-danger"><%= error.full_message %></li>
            <% end %>
        </ul>
    <% end %>
    <div class="form-group mb-3">
        <%= form.label :title, value: t("article_form.title") %>
        <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :content, value: t("article_form.content") %>
        <%= form.rich_text_area :content,class: "form-control" %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :published, value: t("article_form.status") %>
        <%= form.select :published, [[t("article_form.draft"), false], [t("article_form.published"), true]], {}, { :class => 'form-select' } %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :tag_ids, value: t("article_form.tags") %>
        <%= 
            form.select :tag_ids, 
            Tag.pluck(:name,:id), 
            {}, 
            {multiple: true, data: { controller: "slim" } }
        %>
        <%= link_to t("article_form.new_tag_link"), new_tag_path, class:"form-text text-muted"%>
    </div>

    <div class="d-flex flex-row-reverse">
        <div>
            <%= link_to t("article_form.cancel"), :back, class: "btn btn-danger" %>
            <%= form.submit class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

app/views/articles/_article_like_button.html.erb
<% if is_liked?(article,user) %>
    <%= button_to dislike_article_path(article), :class => "btn btn-danger" do %>
        <i class="bi bi-heart-fill"></i>
    <% end %>
<% else %>
    <%= button_to like_article_path(article), :class => "btn btn-secondary" do %>
        <i class="bi bi-heart-fill"></i>
    <% end %>
<% end %>

app/views/articles/_article_list.html.erb
<div class="row">
    <% articles.each do |article| %>
        <div class="col-12 mb-4">
            <%= render partial:"articles/article", locals: { article: article } %>
        </div>
    <% end %>
</div>

app/views/articles/_article_publish_button.html.erb
<% if article.published %>
    <%= button_to unpublish_article_path(article), :class => "btn btn-success" do %>
        <i class="bi bi-bookmark-fill"></i>
    <% end %>
<% else %>
    <%= button_to publish_article_path(article), :class => "btn btn-secondary" do %>
        <i class="bi bi-bookmark-fill"></i>
    <% end %>
<% end %>

app/views/articles/_no_articles.html.erb
<div class="d-flex flex-column align-items-center">
    <h1 class="display-5 text-center"><%= t("no_articles.message")%></h1>
    <% if current_user == user %>
        <%= link_to t("no_articles.new_article"), new_article_path, class: "text-primary display-6" %>
    <% end %>
</div>

app/views/articles/_number_of_comments.html.erb
<%= link_to article_path(article, anchor: "comments") do %>
    <span>
        <i class="bi bi-chat-fill"></i>
        <%= get_number_of_approved_comments_or_current_users_pending_comments(article)%>
    </span>
<% end %>

app/views/articles/_number_of_likes.html.erb
<%= link_to likes_article_path(article) do %>
    <span style="color:red;">
        <i class="bi bi-heart-fill"></i>
        <%= article.article_likes.count %>
    </span>
<% end %>

app/views/articles/edit.html.erb
<div class="row">
    <div class="offset-3 col-6">
        <h3 class="mb-3"><%= t("edit_article.title") %></h3>
        <%= render partial: "article_form", locals: { article: @article } %>
    </div>
</div>

app/views/articles/likes.html.erb
<div class="container">
    <div class="row">
        <div class="offset-md-3 col-md-6">
            <div class="d-flex justify-content-center">
                <h3><%= t("likes.title") %></h3>
            </div>
        </div>
        <div class="offset-md-3 col-md-6">
            <% if @article.users.any? %>
                <%= render partial: "shared/user_items", locals: { users: @article.users } %>
            <% else %>
                <div class="d-flex justify-content-center">
                    <h1> <%= t("likes.no_likes")%> </h1>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<div class="row">
    <div class="offset-3 col-6">
        <h3 class="mb-3"><%= t("create_article.title") %></h3>
        <%= render partial: "articles/article_form", locals: { article: @article } %>
    </div>
</div>

app/views/articles/search.html.erb
<div class="container">
    <div class="row">
        <% if @articles.any? %>
            <% @articles.each do |article| %>
                <div class="col-lg-4 col-md-6 mb-4">
                    <%= render article %>
                </div>
            <% end %>
        <% else %>
            <div class="d-flex justify-content-center">
                <h2><%= t("search.no_articles") %></h2>                
            </div>
        <% end %>
    </div>
</div>

app/views/articles/show.html.erb
<div class="row">
    <div class="offset-md-3 col-md-6">
        <div class="card mb-3">
            <div class="card-header d-flex justify-content-between align-items-center">
                <%= link_to "/#{@article.user.nick_name}" do %>
                    <div class="d-flex align-items-center">
                        <%= render partial:"shared/profile_circle", locals: { user: @article.user, circle: "circle3" }%>
                        <span class="nickname3"><%= format_nick_name(@article.user) %></span>
                    </div>
                <% end %>
                <small class="text-muted m-1">
                    <%= render partial: "article_datetime", locals:{article: @article}%>
                </small>
            </div>

            <img style="border-radius:0" class="card-img-top" src="https://static.vecteezy.com/system/resources/thumbnails/003/582/701/small_2x/coming-soon-background-illustration-template-design-free-vector.jpg" alt="Card image cap">
            
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <h5 class="card-title">
                        <%= @article.title %>
                    </h5>
                    
                    <p class="card-text d-flex align-items-center">
                        <small class="text-muted m-1">
                            <%= render partial: "number_of_likes", locals: { article: @article } %>
                        </small>
                        <small class="text-muted m-1">
                            <%= render partial: "number_of_comments", locals: { article: @article } %>
                        </small>
                    </p>
                </div>
                
                <p class="card-text">
                    <%= article_content(@article) %>
                </p>
                
                <div class="d-flex justify-content-between align-items-center">
                    <% if user_signed_in? %>
                        <%= render partial: "articles/article_like_button", locals:{article: @article,user: current_user} %>
                        <% if @article.user == current_user%>
                            <div class="d-flex">
                                <div class="m-1">
                                    <%= render partial: "article_publish_button",locals: { article: @article } %>
                                </div>
                                <% unless @article.published %>
                                    <div class="m-1">
                                        <%= link_to edit_article_path(@article), class: "btn btn-warning" do %>
                                            <i class="bi bi-pencil-square"></i>
                                        <% end %>
                                    </div>
                                    <div class="m-1">
                                        <%= button_to @article, method: :delete, class: "btn btn-danger" do %>
                                            <i class="bi bi-trash3-fill"></i>
                                        <% end %>
                                    </div>
                                <% end %>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>

        <% if @article.tags.any? %>
            <%= render partial: "tags/tag_list", locals: { tags: @article.tags } %>
        <% end %>

        <% if user_signed_in? %>
            <div class="row mb-5">
                <div class="offset-1 col-10">
                    <%= render partial:"comments/form", locals: { article: @article, comment: Comment.new } %>
                </div>
            </div>
        <% end %>
        
        <div id="comments">
            <%= 
                render partial: "comments/article_comments_list",
                locals: { comments: get_approved_comments_or_current_users_pending_comments(@article) }
            %>
        </div>
    </div>
</div>