config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get "up" => "rails/health#show", as: :rails_health_check

  root "welcome#index"
  
  get ":nick_name", to: "users#show"
  post '/lanugage/change', to: 'language#change'
  
  resources :welcome
  
  resources :tags do
    member do
      get "articles"
    end
  end
    
  resources :profile, only: [] do
    collection do
      get "my_published_articles"
      get "my_draft_articles"

      get "my_comments"
      get "my_rejected_comments"
      get "my_pending_comments"
      get "my_approved_comments"
      
      get "my_received_comments"
      get "my_received_rejected_comments"
      get "my_received_approved_comments"
      get "my_received_pending_comments"
    end
  end

  resources :articles, except: %i[index] do
    member do
      post "publish"
      post "unpublish"
      post "like"
      post "dislike"
      get "likes"
    end

    collection do
      get "search"
    end

    resources :comments do
      member do
        post "mark_as_approved"
        post "mark_as_rejected"
        post "mark_as_pending"
      end
    end
  end

  namespace "api" do
    resources :articles, only: %i[show index]
  end
end

app/views/shared/_profile_circle.html.erb
<div class=<%= circle %>>
    <span style="color:white;"><%= first_letters_of_nick_name(user) %></span>
</div>

app/views/shared/_search_box.html.erb
<%= form_with url: search_articles_path, method: :get, local: true do |form| %>
    <div class="form-check form-switch">
        <%= form.check_box :just_tags, class: "form-check-input", value: params[:just_tags] %>
        <label class="form-check-label">
            <%= t("search_box.just_search_by_tags") %>
        </label>
    </div>
    
    <div class="input-group mb-3">
        <%= form.text_field :keyword, class: "form-control", value: params[:keyword] %>
        <%= form.submit t("search_box.search"), class: "btn btn-outline-secondary" %>
    </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="flex-shrink-0 p-3 bg-white">
    <div class="d-flex">
       <div class="d-flex align-items-center">
            <%= render partial:"shared/profile_circle", locals: { user: current_user, circle: "circle3" }%>
            <span class="nickname3"><%= format_nick_name(current_user) %></span>
        </div>
    </div>
    
    <hr/>
    
    <ul class="list-unstyled ps-0">
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="false">
                <i class="bi bi-book-half"></i>
                <%= t("sidebar.my_articles")%>
            </button>

            <div class="collapse" id="home-collapse" style="">
            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                <li class="sidebar-item">
                    <i class="bi bi-book-half"></i>
                    <%= link_to t("sidebar.my_articles"), "/#{current_user.nick_name}", class:"link-dark rounded" %>
                </li>

                <li class="sidebar-item">
                    <i class="bi bi-book-fill text-secondary"></i>
                    <%= link_to t("sidebar.my_draft_articles"), my_draft_articles_profile_index_path, class:"link-dark rounded" %>
                </li>
                
                <li class="sidebar-item">
                    <i class="bi bi-book-fill text-success"></i>
                    <%= link_to t("sidebar.my_published_articles"), my_published_articles_profile_index_path, class:"link-dark rounded" %>
                </li>
            </ul>
            </div>
        </li>

        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#my-comments-collapse" aria-expanded="false">
                <i class="bi bi-box-arrow-right"></i>
                <%= t("sidebar.my_comments") %>
            </button>
            
            <div class="collapse" id="my-comments-collapse" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li class="sidebar-item">
                        <i class="bi bi-chat-square"></i>
                        <%= link_to t("sidebar.my_comments"), my_comments_profile_index_path, class:"link-dark rounded" %>
                    </li>

                    <li class="sidebar-item">
                        <i class="bi bi-chat-square-fill text-danger"></i>
                        <%= link_to t("sidebar.my_rejected_comments"), my_rejected_comments_profile_index_path, class:"link-dark rounded" %>
                    </li>
                    
                    <li class="sidebar-item">
                        <i class="bi bi-chat-square-fill text-warning"></i>
                        <%= link_to t("sidebar.my_pending_comments"), my_pending_comments_profile_index_path, class:"link-dark rounded" %>
                    </li>
                    
                    <li class="sidebar-item">
                        <i class="bi bi-chat-square-fill text-success"></i>
                        <%= link_to t("sidebar.my_approved_comments"), my_approved_comments_profile_index_path, class:"link-dark rounded" %>
                    </li>
                </ul>
            </div>
        </li>

        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#other-comments-collapse" aria-expanded="false">
                <i class="bi bi-box-arrow-in-left"></i>
                <%= t("sidebar.comments_on_my_articles") %>
            </button>
            
            <div class="collapse" id="other-comments-collapse" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li class="sidebar-item">
                        <i class="bi bi-chat-square"></i>
                        <%= link_to t("sidebar.comments_on_my_articles"),  my_received_comments_profile_index_path, class:"link-dark rounded" %>
                    </li>

                    <li class="sidebar-item">
                        <i class="bi bi-chat-square-fill text-danger"></i>
                        <%= link_to t("sidebar.rejected_comments_on_my_articles"), my_received_rejected_comments_profile_index_path, class:"link-dark rounded" %>
                    </li>
                    
                    <li class="sidebar-item">
                        <i class="bi bi-chat-square-fill text-warning"></i>
                        <%= link_to t("sidebar.pending_comments_on_my_articles"), my_received_pending_comments_profile_index_path, class:"link-dark rounded" %>
                    </li>
                    
                    <li class="sidebar-item">
                        <i class="bi bi-chat-square-fill text-success"></i>
                        <%= link_to t("sidebar.approved_comments_on_my_articles"), my_received_approved_comments_profile_index_path, class:"link-dark rounded" %>
                    </li>
                </ul>
            </div>
        </li>
    
        <li class="border-top my-3"></li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
                <i class="bi bi-person-gear"></i>
                <%= t("sidebar.account") %>
            </button>
            
            <div class="collapse" id="account-collapse">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li class="sidebar-item">
                        <i class="bi bi-gear"></i>
                        <%= link_to t("sidebar.edit_your_account"), edit_user_registration_path, class: "link-dark rounded" %>
                    </li>

                    <li class="sidebar-item">
                        <i class="bi bi-door-open-fill"></i>
                        <%= link_to t("sidebar.sign_out"), destroy_user_session_path, method: :delete,data: { turbo_method: :delete }, class: "link-dark rounded"%>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</div>

app/views/shared/_user_item.html.erb
<div class="card mb-3 p-2">
  <div class="d-flex align-items-center">
    <%= link_to "/#{user.nick_name}" do %>
      <%= render partial: "shared/profile_circle", locals: { user: user, circle: "circle2" } %>
    <% end %>
    <%= link_to "/#{user.nick_name}" do %>
      <span class="nickname2">
        <%= format_nick_name(user)%>
      </span>
    <% end %>
  </div>
</div>

app/views/shared/_user_items.html.erb
<div>
  <% users.each do |user| %>
    <%= render partial: "shared/user_item", locals: { user: user } %>
  <% end %>
</div>