config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get "up" => "rails/health#show", as: :rails_health_check

  root "welcome#index"
  
  get ":nick_name", to: "users#show"
  post '/lanugage/change', to: 'language#change'
  
  resources :welcome
  
  resources :tags do
    member do
      get "articles"
    end
  end
    
  resources :profile, only: [] do
    collection do
      get "my_published_articles"
      get "my_draft_articles"

      get "my_comments"
      get "my_rejected_comments"
      get "my_pending_comments"
      get "my_approved_comments"
      
      get "my_received_comments"
      get "my_received_rejected_comments"
      get "my_received_approved_comments"
      get "my_received_pending_comments"
    end
  end

  resources :articles, except: %i[index] do
    member do
      post "publish"
      post "unpublish"
      post "like"
      post "dislike"
      get "likes"
    end

    collection do
      get "search"
    end

    resources :comments do
      member do
        post "mark_as_approved"
        post "mark_as_rejected"
        post "mark_as_pending"
      end
    end
  end

  namespace "api" do
    resources :articles, only: %i[show index]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :article_tags, dependent: :destroy
    has_many :articles, through: :article_tags
    validates :name, uniqueness: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_action :authenticate_user!, except: %i[articles]

    def create
        @tag = Tag.new(tag_params)
        if @tag.save
            redirect_to new_article_path, notice: "The tag has been successfully created."
        else
            render :new, status: :unprocessable_entity
        end
    end

    def new
        @tag = Tag.new
    end

    def articles
        @tag = Tag.find(params[:id])
        @articles = @tag.articles.where(published: true).order(created_at: :desc)
    end

    private
        def tag_params
            params.require(:tag).permit(:name)
        end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
    
    <% if tag.errors.any? %>
        <ul class="list-group mb-3">
            <% tag.errors.each do |error| %>
                <li class="list-group-item list-group-item-danger"><%= error.full_message %></li>
            <% end %>
        </ul>
    <% end %>
    
    <div class="form-group mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
    </div>
   
    <div class="d-flex flex-row-reverse">
        <div>
            <%= link_to 'Cancel', :back, class: "btn btn-danger" %>
            <%= form.submit class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

app/views/tags/_tag_list.html.erb
<div class="d-flex card mb-5 p-1">
    <div class="card-body">
        <% tags.each do |tag| %>
            <button class="btn btn-warning d-flex align-items-center m-1">
                <%= link_to articles_tag_path(tag) do %>
                    <i class="bi bi-tag"></i><%= tag.name %>
                <% end %>
            </button>
        <% end %>
    </div>
</div>

app/views/tags/articles.html.erb
<div class="container">
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <h1 class="text-">
                <%= "##{@tag.name}" %>
            </h1>
        </div>
        <div class="offset-md-2 col-md-8 offset-lg-3 col-lg-6">
            <%= render partial: "/articles/article_list", locals: { articles: @articles }%>
        </div>
    </div>
</div>

app/views/tags/new.html.erb
<div class="row">
    <div class="offset-3 col-6">
        <h3 class="mb-3">Create A New Tag</h3>
        <%= render partial: "tags/form", locals: { tag: @tag } %>
    </div>
</div>